### ISSUE TITLE
Seperate SLIP node?

### ISSUE THREAD

**Issue by njh** [njh/node-red-contrib-osc#10]
@natcl maybe this is a crazy idea, but is crossed my mind that SLIP encapsulation may have other use cases, other than OSC?
- Would it be weird to have a seperate SLIP node?
- Would it be possible to detect encodes and decodes? String v. Buffer? Or perhaps check for 0xC0 on the beginning/end?

**Comment by natcl** [comment]
I had the same idea but decided to include it in the node for sake of simplicity.  However I'm not against the idea as this could indeed be useful for some use cases. It's a little more work for the user but serial/tcp usage is not the most used scenario so perhaps it's not that annoying.  The one thing that concerns me is for the examples, if we make it a separate NPM package I wonder if a node can include a node-red node in it's package.json and make it available to Node-RED ? I'll have to test.  It would be nice if the slip node was installed automatically with the osc node but still be separate on npm.  

I'm pretty sure we could detect encodes/decodes.  It would also make the osc code cleaner.  Will give it some thought !

**Comment by njh** [comment]
Done!

I didn't do automatic detection in the end - I am not sure it can be done reliably.
Incoming serial streams can very legitimately not include a 0xC0 on the beginning or end - but should be buffered until one is seen.

https://github.com/njh/node-red-contrib-slip

**Comment by njh** [comment]
Hm! I have just been testing this and listing node-red-contrib-slip as a dependency is not enough to make it appear in the list of available node types.

**Comment by natcl** [comment]
Yes, Nick told me it doesn't work yet but might be possible with npm3. I guess we can just mention how to install the node in the instructions.

**Comment by njh** [comment]
I updated the README: https://github.com/njh/node-red-contrib-osc
