### ISSUE TITLE
Behringer X32 /xremote command doesn't send no messages.

### ISSUE THREAD

**Issue by nfavrod** [njh/node-red-contrib-osc#12]
Hello,

I use for a few days your OSC node Red Flow and it's really a great great thing for me!

I have a problem to send to my mixer behringer X32 all the commands that haven't any args. I tried to set the payload null or "" but no way :(

I therefore can't achieve to receive the OSC commands from my mixer because it needs to be activated with the /xremote command withou args. You can find information there : https://sites.google.com/site/patrickmaillot/docs/X32-OSC.pdf

Can you help me find how to encode the OSC message /xremote ou /info or /status

**Comment by natcl** [comment]
Can you send an example flow with the commands you tried to send ?

**Comment by nfavrod** [comment]
Hello,

Here's a simple example : 

`[{"id":"9421282d.fb3ce","type":"inject","z":"97c1ea68.c11b08","name":"","topic":"/xremote","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"x":123,"y":233.25,"wires":[["5cdb3a64.12d5e4"]]},{"id":"dfe7bc6.6ae654","type":"debug","z":"97c1ea68.c11b08","name":"","active":true,"console":"false","complete":"false","x":561,"y":311.5,"wires":[]},{"id":"9b02ff12.9d29","type":"debug","z":"97c1ea68.c11b08","name":"","active":true,"console":"false","complete":"true","x":552,"y":378,"wires":[]},{"id":"5cdb3a64.12d5e4","type":"osc","z":"97c1ea68.c11b08","name":"","path":"","metadata":false,"x":311,"y":223.75,"wires":[["459e1a99.61a9a4","9b02ff12.9d29","dfe7bc6.6ae654"]]},{"id":"4c5ef4e1.97d54c","type":"osc","z":"97c1ea68.c11b08","name":"","path":"","metadata":false,"x":307,"y":381.75,"wires":[["9b02ff12.9d29"]]},{"id":"459e1a99.61a9a4","type":"udp out","z":"97c1ea68.c11b08","name":"","addr":"192.168.20.10","iface":"","port":"10023","ipv":"udp4","outport":"","base64":false,"multicast":"false","x":542,"y":227.5,"wires":[]},{"id":"87dbd3e1.ba1c6","type":"udp in","z":"97c1ea68.c11b08","name":"","iface":"","port":"10023","ipv":"udp4","multicast":"false","group":"","datatype":"buffer","x":115,"y":382.25,"wires":[["4c5ef4e1.97d54c"]]}]`

**Comment by natcl** [comment]
Please try this:

```
[{"id":"bc16822f.49998","type":"debug","z":"9a32c934.5d6af","name":"","active":true,"console":"false","complete":"payload","x":889,"y":264.75,"wires":[]},{"id":"a30d9a64.efad6","type":"osc","z":"9a32c934.5d6af","name":"","path":"","metadata":false,"x":628,"y":110.5,"wires":[["aed71f7f.2d1c9"]]},{"id":"fef80885.25c7b8","type":"osc","z":"9a32c934.5d6af","name":"","path":"","metadata":true,"x":624,"y":268.5,"wires":[["bc16822f.49998"]]},{"id":"aed71f7f.2d1c9","type":"udp out","z":"9a32c934.5d6af","name":"","addr":"localhost","iface":"","port":"10023","ipv":"udp4","outport":"","base64":false,"multicast":"false","x":849,"y":114.25,"wires":[]},{"id":"714962e1.5fee04","type":"udp in","z":"9a32c934.5d6af","name":"","iface":"","port":"10023","ipv":"udp4","multicast":"false","group":"","datatype":"buffer","x":432,"y":269,"wires":[["fef80885.25c7b8"]]},{"id":"969bc568.2b3aa","type":"inject","z":"9a32c934.5d6af","name":"","topic":"/xremote","payload":"null","payloadType":"json","repeat":"","crontab":"","once":false,"x":450,"y":120,"wires":[["a30d9a64.efad6"]]}]
```

**Comment by nfavrod** [comment]
Sorry doesn't work... I tried also making a function to set payload to null but no way...

There's an emulator of the X32 console for all platform to download here : https://sites.google.com/site/patrickmaillot/x32

**Comment by natcl** [comment]
Can you send the command from something that you know works to node-red with the include metadata checkbox checked so we can see the exact message that works ?

**Comment by nfavrod** [comment]
Here's a command that sends a command to setup DCA Fader n°1  to 1 (0db) : 

`[{"id":"4e528789.ba1788","type":"debug","z":"97c1ea68.c11b08","name":"","active":true,"console":"false","complete":"payload","x":656,"y":373,"wires":[]},{"id":"83b74179.0795a8","type":"osc","z":"97c1ea68.c11b08","name":"","path":"","metadata":true,"x":395,"y":218.75,"wires":[["b43dc70e.ab151"]]},{"id":"7b43295b.dc1228","type":"osc","z":"97c1ea68.c11b08","name":"","path":"","metadata":true,"x":391,"y":376.75,"wires":[["4e528789.ba1788"]]},{"id":"b43dc70e.ab151","type":"udp out","z":"97c1ea68.c11b08","name":"","addr":"localhost","iface":"","port":"10023","ipv":"udp4","outport":"","base64":false,"multicast":"false","x":616,"y":222.5,"wires":[]},{"id":"e8a7ae67.d7aed","type":"udp in","z":"97c1ea68.c11b08","name":"","iface":"","port":"10023","ipv":"udp4","multicast":"false","group":"","datatype":"buffer","x":199,"y":377.25,"wires":[["7b43295b.dc1228"]]},{"id":"2852b569.035122","type":"inject","z":"97c1ea68.c11b08","name":"","topic":"/dca/1/fader","payload":"1","payloadType":"num","repeat":"","crontab":"","once":false,"x":214,"y":219,"wires":[["83b74179.0795a8"]]}]`

**Comment by natcl** [comment]
But the /xremote command that doesn't work, are you able to send it from another software ?

**Comment by nfavrod** [comment]
Yes, but not so shure actually : 

here something that works  with the /status command, but not the /xremote : 

`[{"id":"83b74179.0795a8","type":"osc","z":"97c1ea68.c11b08","name":"","path":"","metadata":true,"x":372,"y":215.75,"wires":[["b43dc70e.ab151"]]},{"id":"b43dc70e.ab151","type":"udp out","z":"97c1ea68.c11b08","name":"","addr":"localhost","iface":"","port":"10023","ipv":"udp4","outport":"","base64":false,"multicast":"false","x":616,"y":150.5,"wires":[]},{"id":"2852b569.035122","type":"inject","z":"97c1ea68.c11b08","name":"","topic":"/dca/1/fader","payload":"1","payloadType":"num","repeat":"","crontab":"","once":false,"x":188,"y":221,"wires":[["83b74179.0795a8"]]},{"id":"cb236c22.1a04f8","type":"inject","z":"97c1ea68.c11b08","name":"","topic":"","payload":"/xremote","payloadType":"str","repeat":"","crontab":"","once":false,"x":222,"y":122,"wires":[["7f02ce24.96afe8"]]},{"id":"7f02ce24.96afe8","type":"function","z":"97c1ea68.c11b08","name":"","func":"msg.payload = new Buffer(msg.payload);\nreturn msg;","outputs":1,"noerr":0,"x":400,"y":150.5,"wires":[["b43dc70e.ab151"]]},{"id":"a164a6b9.5036b","type":"inject","z":"97c1ea68.c11b08","name":"","topic":"","payload":"/status","payloadType":"str","repeat":"","crontab":"","once":false,"x":219,"y":162.25,"wires":[["7f02ce24.96afe8"]]}]`

The output of the terminal is : 
' /xremote~~~~ (4 times ~ but it won't show here) '

**Comment by natcl** [comment]
In the last example you sent your are putting the address in the payload but It should be in the topic, the payload field is for the actual data. You cannot send something with an empty adress using osc...

**Comment by nfavrod** [comment]
Thanks for your answer. 
Yes, I verified this, but I actually tried to send directly the payload as 12 bytes Buffer to the UDP socket... but it doesn't work either...
I don't manage to make the /xremote command outside of the X32 utility. With no other software.
I will ask the developper if he can help, and will post here the answer! 
Thanks

**Comment by natcl** [comment]
Normally this should work:
```
[{"id":"a30d9a64.efad6","type":"osc","z":"9a32c934.5d6af","name":"","path":"","metadata":false,"x":628,"y":110.5,"wires":[["aed71f7f.2d1c9"]]},{"id":"aed71f7f.2d1c9","type":"udp out","z":"9a32c934.5d6af","name":"","addr":"localhost","iface":"","port":"10023","ipv":"udp4","outport":"","base64":false,"multicast":"false","x":849,"y":114.25,"wires":[]},{"id":"969bc568.2b3aa","type":"inject","z":"9a32c934.5d6af","name":"","topic":"/xremote","payload":"null","payloadType":"json","repeat":"","crontab":"","once":false,"x":430,"y":80,"wires":[["a30d9a64.efad6"]]}]
```
That's the correct way to send a message without data in OSC.
But make sure you change the IP address...
Also note that the message type is json, not string.

**Comment by nfavrod** [comment]
Thanks a lot!
I wonder if it's something with the table cause when I bypass all I received the message correctly. 
I think I don't understand in the OSC server of the X32, cause I'm able to manage this with TouchOSC.

**Comment by nfavrod** [comment]
So we finally found the solution, thanks to @pmaillot 👍 

The /xremote doesn't send back the infos when it's the same client that sends commands.

As I wanted to group all my OSC commands on Node Red, as an OSC Routeur, that's why the X32 never answered, and I had to connect another device directly to the X32 to receive any messages from the console.

We found that for the /xremote command, all differents OSC messages works like : /xremote~~~~,N~~~ that is the one with JSON : null. But also if you put Float or String empty.

Thanks for helping you all!

**Comment by nfavrod** [comment]
Notice that to receive correctly the informations from the X32 like with /status ou /xinfo, you need to "bind your local port" your UDP connection, otherwise the X32 answer on random port.

**Comment by terwarf** [comment]
Just as a note here for future visitors:
to fully omit the message body you need to have a msg without the payload field.

In the inject node it should look like this:
![grafik](https://user-images.githubusercontent.com/2771041/94346155-102e5e00-002b-11eb-8fb7-c459f060c702.png)
(this is to request the value of a fader a single time)

this is the node setup and the resulting msg object:
![grafik](https://user-images.githubusercontent.com/2771041/94346381-9dbe7d80-002c-11eb-81b5-22234a633b4d.png)




a Json input with null results in `/ch/01/mix/fader~~~~,N~~` which the x32 won't respond to.
A msg without payload results in `/ch/01/mix/fader~~~~,~~~` which gives the correct answer.
(Tested with wireshark)
