### ISSUE TITLE
Module version mismatch

### ISSUE THREAD

**Issue by Hugobox** [njh/node-red-contrib-osc#13]
Hi!
I installed locally via "npm install node-red-contrib-osc" and in the console I get: 

 [osc] Error: Module version mismatch. Expected 48, got 46.

Then the node doesn't appear in the editor. Tried on 2 different machines, same result.
Thanks!

**Comment by njh** [comment]
Hello,

Sorry, I have not seen the error "Module version mismatch. Expected 48, got 46" before.

Googling it seems to imply that it has something to do with having two different versions of node/npm on the same system: 

https://www.google.co.uk/search?q=Module+version+mismatch.+Expected+48%2C+got+46

For example this:
http://blog.jonathanargentiero.com/node-js-error-module-version-mismatch-expected-48-got-46/

nick.

**Comment by Hugobox** [comment]
Thanks Nick! I will follow-up on this early next week.

**Comment by frantic0** [comment]
Hi,

same here, got this log after installing 

7 Jun 17:14:10 - [warn] [osc] Error: Module version mismatch. Expected 48, got 51.

I'm running 

7 Jun 17:14:09 - [info] Node-RED version: v0.16.2
7 Jun 17:14:09 - [info] Node.js  version: v6.11.0

@Hugobox did you sort out the problem ?

**Comment by eighteight** [comment]
I had this problem. Fixed it by finding node_modules directories in various places, which I then cleaned to fix it
