### ISSUE TITLE
Publish most recent version to npmjs

### ISSUE THREAD

**Issue by stevenaeola** [njh/node-red-contrib-osc#19]
Hi there. I've got a pre-release version of node-red-contrib-music on npmjs, which relies on node-red-contrib-osc. For best functionality, particularly on a Raspberry Pi, it needs to use OSC bundling, which I added in my pull request. I'm using this for a workshop in a school on 5/6th July so it would be great to have it by then.

**Comment by natcl** [comment]
Hmm bundles already work can you elaborate on what you added ?

**Comment by njh** [comment]
@natcl this Pull Request: #14

**Comment by natcl** [comment]
Ah got it !
Yeah I see no problem in doing a release with those changes.

**Comment by njh** [comment]
After doing a bit of manual testing I have published version 1.1.0:
* https://github.com/njh/node-red-contrib-osc/tree/1.1.0
* https://www.npmjs.com/package/node-red-contrib-osc/v/1.1.0

**Comment by stevenaeola** [comment]
Thanks!
