### ISSUE TITLE
Node-red crashes if port is already in use

### ISSUE THREAD

**Issue by natcl** [njh/node-red-contrib-osc#2]
It seems like the osc node makes node-red crash if you attempt to use a port that is already in use, see this error log:

```
15 Feb 13:05:34 - [red] Uncaught Exception:
15 Feb 13:05:34 - Error: bind EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at dgram.js:224:28
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
```

**Comment by takaji10** [comment]
I was getting very frustrated with this until I realized what was happening. For anyone wanting to fix this for the short-term, you need to edit your node-red flows file and remove the conflicting OSC node manually. Hopefully there's an eventual fix for this.

**Comment by njh** [comment]
I applied your Pull Request and published a new version of the node.

Note that I renamed it to be consistent with the Node-RED packaging guide:
https://www.npmjs.com/package/node-red-contrib-osc

Thanks for reporting and fixing :)

**Comment by natcl** [comment]
Many thanks !
