### ISSUE TITLE
install the package on windows fails

### ISSUE THREAD

**Issue by le-ross** [njh/node-red-contrib-osc#20]
21 Jun 11:14:27 - [info] Installed module: node-red-contrib-osc
21 Jun 11:14:27 - [info] Added node types:
21 Jun 11:14:27 - [info]  - node-red-contrib-osc:osc : Error: %1 is not a valid Win32 application.
[...] \node_modules\serialport\build\Release\serialport.node

I am not sure why i need to support serial to handle osc?

**Comment by natcl** [comment]
This is a problem with the upstream osc.js package which requires different libraries, the author is working on separating the osc.js library in different modules which should solve this issue.
This should still work under windows though as the serialport should be able to build. what version of windows are you using ?

**Comment by njh** [comment]
I am actually now having problems with getting osc.js to install on my Mac due to problems with serialport. Very annoying when node-red-contrib-osc doesn't even use that functionality.

**Comment by natcl** [comment]
What errors are you getting on Mac ?
I could have a look at the upstream library to see how difficult it would be to fork out the parse/encode functions.
Although serial should still build fine on Mac.

**Comment by njh** [comment]
I was getting errors like this:

```
23 Jun 15:28:42 - [warn] [node-red-contrib-osc/osc] Error: Could not locate the bindings file. Tried:
 → node-red-contrib-osc/node_modules/osc/node_modules/serialport/build/serialport.node
 → node-red-contrib-osc/node_modules/osc/node_modules/serialport/build/Debug/serialport.node
 → node-red-contrib-osc/node_modules/osc/node_modules/serialport/build/Release/serialport.node
 → node-red-contrib-osc/node_modules/osc/node_modules/serialport/out/Debug/serialport.node
 → node-red-contrib-osc/node_modules/osc/node_modules/serialport/Debug/serialport.node
 → node-red-contrib-osc/node_modules/osc/node_modules/serialport/out/Release/serialport.node
 → node-red-contrib-osc/node_modules/osc/node_modules/serialport/Release/serialport.node
 → node-red-contrib-osc/node_modules/osc/node_modules/serialport/build/default/serialport.node
 → node-red-contrib-osc/node_modules/osc/node_modules/serialport/compiled/8.11.3/darwin/x64/serialport.node
 ```

I have now downgraded to Node v6.14.3 (`brew install node@6`) and it is working again.
No idea if downgrading to node 6 might also fix Windows.

**Comment by natcl** [comment]
Thanks will try it on my side to see if there's a workaround for node 8.x


--
lecaude.com 
studioimaginaire.com

**Comment by natcl** [comment]
I have a feeling it might be related to an old version being still present in `node_modules`.  On my mac I was able to install:

```
MacBook-Pro:osctest Nat$ node -v
v8.11.3
MacBook-Pro:osctest Nat$ npm -v
6.1.0
MacBook-Pro:osctest Nat$ npm install node-red-contrib-osc

> serialport@6.2.0 install /Users/Nat/Desktop/osctest/node_modules/serialport
> prebuild-install || node-gyp rebuild

npm WARN saveError ENOENT: no such file or directory, open '/Users/Nat/Desktop/osctest/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/Nat/Desktop/osctest/package.json'
npm WARN osctest No description
npm WARN osctest No repository field.
npm WARN osctest No README data
npm WARN osctest No license field.

+ node-red-contrib-osc@1.1.0
added 200 packages from 85 contributors and audited 513 packages in 6.798s
found 0 vulnerabilities
```

**Comment by ghost** [comment]
Unfortunatly I wasnt
Node Version 11.10.0

```
Larss-MacBook-Pro:~ larskmann$ sudo npm install node-red-contrib-osc
Password:
serialport@6.2.2 install /Users/larskmann/node_modules/serialport
prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=11.10.0 runtime=node arch=x64 platform=darwin)
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/larskmann/node_modules/serialport/build'
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/larskmann/node_modules/serialport
gyp ERR! node -v v11.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/Users/larskmann/package.json'
npm WARN larskmann No description
npm WARN larskmann No repository field.
npm WARN larskmann No README data
npm WARN larskmann No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serialport@6.2.2 install: prebuild-install || node-gyp rebuild
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@6.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/larskmann/.npm/_logs/2019-02-19T22_56_29_194Z-debug.log
```

**Comment by njh** [comment]
@larskmann that looks like a Mac, not Windows?

**Comment by natcl** [comment]
Perhaps try with the --unsafe-perm flag when you npm install

**Comment by ghost** [comment]
yes, only posted here because of the previous post also being from a mac. but i also have to say i am only using it on mac right now becaouse the raspberry is use right now and my only pc left is a mac :)

**Comment by natcl** [comment]
is that with node 11?

**Comment by ghost** [comment]
yes

**Comment by ghost** [comment]
> Perhaps try with the --unsafe-perm flag when you npm install

same same

**Comment by njh** [comment]
Sorry to be brutal and close this, please can you open a new issue - it doesn't look related to me

**Comment by natcl** [comment]
Node-RED supports node 8.x for the moment, can you try with that?
