### ISSUE TITLE
msg.payload formatting

### ISSUE THREAD

**Issue by dmgoldstein1** [njh/node-red-contrib-osc#24]
Hello,
I'm new to Node-RED and so this is probably a very elementary question. Right now I'm just trying to learn how to properly format msg.payload so it can carry _multiple strings_.  My use case is to send OSC commands to [ZoomOSC](https://www.liminalet.com/zoomosc). I am using [Protokol] (https://hexler.net/protokol) to get visibility into how my OSC is formatted. I have successfully used [TouchOSC](https://hexler.net/touchosc) to send OSC commands that do what I want them to.  For my testing purposes, I am trying to send a chat to Bob that says "Hello world". This is what Protokol looks like when the command is formatted properly from TouchOSC:

<img width="653" alt="protokol" src="https://user-images.githubusercontent.com/96954562/147880587-f0d30d32-dcf7-40ea-a06d-de39259ed618.png">

You can see that there are multiple strings, marked in purple.  I have so far been unable to figure out how to do the same with the node from node-red-contrib-osc.  I have been able to successfully send OSC messages to ZoomOSC that do not have any strings, only an address, so I know my networking is correct, etc.  It's the strings part that I'm not able to get right. Here's what I have in my flow:

<img width="974" alt="node red osc attempt" src="https://user-images.githubusercontent.com/96954562/147881108-f98a6344-85c8-4890-8f8b-32e3d5b83226.png">

with my injected syntax as this:

<img width="554" alt="inject payload syntax" src="https://user-images.githubusercontent.com/96954562/147881158-32a0159e-afc1-400e-855b-3afe0d511801.png">

Could someone help me understand how to format msg.payload properly, so the end result is what is seen in my first image? Should the object be a string, JSON, etc.? Do I use quotation marks, curly braces, etc.?  I'd appreciate any help.  Thank you so much!

**Comment by natcl** [comment]
You need to send it as a JSON Array:
![osc](https://user-images.githubusercontent.com/77556/147883428-99320f74-e89a-46d7-950b-1c0f6d228f85.png)
)

**Comment by dmgoldstein1** [comment]
> You need to send it as a JSON Array: ![osc](https://user-images.githubusercontent.com/77556/147883428-99320f74-e89a-46d7-950b-1c0f6d228f85.png) )

Thank you so much natcl. That's exactly the information I was looking for!
