### ISSUE TITLE
Fix: Error: Bad socket type specified. Valid types are: udp4, udp6

### ISSUE THREAD

**Issue by artelse** [njh/node-red-contrib-osc#4]
This error appears on RaspberryPi "Error: Bad socket type specified. Valid types are: udp4, udp6" when sending on OSC. 
This can be fixed by updating node-osc to version 2.0.3 from 1.0.2.
Maintainer therefore should update node-osc dependency to 2.0.3.
Thanks!

**Comment by njh** [comment]
Bumped up node-osc version number in 21ef60d93f78c10bd29b448dbf30777a41d4dc85

**Comment by njh** [comment]
Published version 0.0.6:
https://www.npmjs.com/package/node-red-contrib-osc
