### ISSUE TITLE
Transport independant OSC

### ISSUE THREAD

**Issue by natcl** [njh/node-red-contrib-osc#5]
Hi there.
I was thinking about starting work on a transport independant osc node for Node-RED and was wondering if you would be interested in merging my code eventually ? 

The reason I want to do this is that I would rather use Node-RED's builtin transports (udp, tcp, serial, websockets) rather than having UDP as the only option.  This would obviously not be backwards compatible with your current implementation.
This would also fix the issue of broadcast not working over UDP.

Let me know if you'd be interested in this, if not I would create a separate osc object but I think it's always better to have a single one for clarity.

**Comment by njh** [comment]
Hi,

Yes, I totally agree. Much better to have a single OSC node type.

So the new module would just do JSON -> OSC binary protocol conversion?
Sounds like a good idea... happy for it to be version 1.0.0 of this module.

Just need to make sure that the documentation makes it clear how you move to the new version.

nick.

**Comment by natcl** [comment]
Hi !
Yes it would only do the conversion.  A little slower to use than the current version but would offer more possibilities.  I would also do the SLIP encoding within the node for when working with Serial and TCP streams.

I'll start working on a fork and let you know when I have something to test. 
Thanks !

**Comment by njh** [comment]
Done a few tweaks and merged your branch into master.

Can you test to see if it works for you still?

There are some complex paths though this code.
I am missing unit tests :(

**Comment by natcl** [comment]
Thanks, testing this morning

Le mer. 1 juin 2016 à 19:39, Nicholas Humfrey notifications@github.com a
écrit :

**Comment by natcl** [comment]
Tested and it seems to work fine.  I just wrote a fix to send numbers larger than 4294967296 (int32), will send a PR.

**Comment by natcl** [comment]
Not rocket science, but with the new nodes we can send/receive OSC over mqtt without any conversion:
![osc_to_mqtt](http://g.recordit.co/XGU3JPIycv.gif)

**Comment by natcl** [comment]
Been using the newer version for a while now and it seems pretty reliable, would it be time to publish it to npm ?

**Comment by natcl** [comment]
Any news ?

**Comment by njh** [comment]
I am still not happy with the automatic type detection - really don't think it belongs in the Node-RED code but colinbdclark doesn't want it in his library either.

Annoyingly I think I went on holiday just after colin replied and I didn't follow up.

Because node-red nodes should be all about the user-interface, or glue, they are quite hard to write unit tests for and verify behavior. One possibility is to create an OSC 'autodetect' library, that sits between the two?

**Comment by natcl** [comment]
I think it would over complicate things. Most of the softwares I use that
have OSC do the type detection automatically (max/msp, pure data, touch
designer)

I think the actual implementation works well, it detects the type and if
you really want a specific type for your use case you send an object
instead of the raw value.
Le dim. 9 oct. 2016 à 17:50, Nicholas Humfrey notifications@github.com a
écrit :

**Comment by natcl** [comment]
That being said I agree the large number detection shouldn't be done in
node-red, from what I saw the previous osc lib didn't play well either with
large numbers.

**Comment by njh** [comment]
Yes, I agree. Not good to make things more complex than they need to be.
I might raise an issue with osc.js about improving the auto-detection.

I think #8 just needs to be resolved and then make a new release of node-red-contrib-osc.

**Comment by njh** [comment]
Just updated the screenshot and published version 1.0.0 (at last!)

https://www.npmjs.com/package/node-red-contrib-osc

**Comment by natcl** [comment]
Thanks ! Nice team work ! :)
Le dim. 16 oct. 2016 à 07:39, Nicholas Humfrey notifications@github.com a
écrit :
